const PORT=process.env.PORT || 5000
const dotenv=require('dotenv')
dotenv.config()
const express=require('express')
const app=express()
const connectDB=require('./config/db')
const itemRouter=require('./routes/itemRoute')
const userRouter=require('./routes/userRoute')
const router = require('./routes/collectionRoute')
const authRouter = require('./routes/authRoute')
const dashboardRoute=require('./routes/dashboardRoute')
const activityRouter = require('./routes/activityRoute')
connectDB()
app.use(express.json())
app.use('/api', itemRouter )
app.use('/api', userRouter)
app.use('/api', router )
app.use('/api', authRouter)
app.use('/api', dashboardRoute)
app.use('/api', activityRouter)
app.listen(PORT, ()=>
{
    console.log('Server Started Successfully!')
})